- type: replace  
  path: /az-configuration?
  value: [${az_configuration}]

- type: replace  
  path: /networks-configuration?
  value:
    icmp_checks_enabled: false
    networks:
    - name: management
      subnets: ${management_subnets}

- type: replace  
  path: /properties-configuration/iaas_configuration?/project?
  value: ${project}

- type: replace  
  path: /properties-configuration/iaas_configuration?/associated_service_account?
  value: ${service_account}